env:
  global:
    - CC_TEST_REPORTER_ID=7ce460d039732b97d7bb74401b1f3a51bb0d37a858f67f7a11323fc5fa853edd
language: java

before_script:
  - curl -L https://codeclimate.com/github/xeniaka/json-diff > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - bundle exec rspec
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT