CREATE TABLE json_data (
  id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1),
  object_identifier VARCHAR(255) NOT NULL,
  position VARCHAR(5) NOT NULL,
  value VARCHAR(255) NOT NULL, -- consider using CLOB if storing very large strings.
  PRIMARY KEY (id)
);
